Args <- commandArgs(TRUE)
library(edgeR) 
targets <- read.delim(file = "ta_targets.txt", stringsAsFactors = FALSE) 
d <- readDGE(targets, columns=c(2,1))
d <- d[rowSums(d$counts) > 1*nrow(targets), ]
png('ta_MDS_non_normalized.png')
plotMDS.dge(d, main='MDS Plot non normalized on ta-sites', xlim=c(-3,3), ylim=c(-3,3))
dev.off()
d <- calcNormFactors(d, method=c(Args[1]))
d <- estimateCommonDisp(d) 
png('ta_MDS_normalized.png')
plotMDS.dge(d, main='MDS Plot normalized on ta-sites', xlim=c(-3,3), ylim=c(-3,3))
dev.off()
d <- estimateTagwiseDisp(d, prior.n=5, prop.used=0.2)
de.tagwise <-exactTest(d, common.disp = FALSE) 
toptags_tgw.out <-topTags(de.tagwise, n=nrow(de.tagwise)+1) 
write.table(d$samples, 'ta_samples.tsv', sep = "\t", quote=FALSE, col.names = NA, row.names = TRUE)
detags200 <- rownames(topTags(de.tagwise, n = 200)$table)
png('ta_plot.png')
plotSmear(d, de.tags = detags200, main = 'Fold change plot using tagwise dispersion on ta sites')
abline(h = c(-2, 2), col = 'dodgerblue')
dev.off()
allcounts.merged <- merge(d$counts, d$pseudo.alt, by=0)
row.names(allcounts.merged) <- allcounts.merged[, 1]
allcounts.merged <- allcounts.merged[, 2:(2 * nrow(targets)+1)]
alldata.merged <- merge(allcounts.merged, toptags_tgw.out$table, by=0)
genefunctions <- read.delim("ta.ptt", header=F) 
alloutput.merged <- merge (alldata.merged, genefunctions, by=1, all.x=TRUE) 
write.table(alloutput.merged, 'ta_alloutputmerged.tsv', sep = "\t", quote=FALSE, col.names = NA, row.names = TRUE) 
q() 
